### PR TITLE
make sure oembed won't mess with the indexing anymore

### PR DESCRIPTION
**Pull request by ivankristianto**
Make sure other oembed like instagram, twitter, youtube, etc... won't cause the problem when indexing

### CODE REVIEW

**Comment by tlovett1** [comment]
Was there another error happening? I thought we fixed this?

**Comment by ivankristianto** [comment]
@tlovett1 yes I found it yesterday.
Where Instagram url embed will cause the indexing with infinite loop again.
I disable all the oembed filter from the the_content to make sure it doesn't happen again

**Comment by tlovett1** [comment]
Does removing the_content fix this?

**Comment by ivankristianto** [comment]
Yes, if we merge this #764 
then this PR is not necessary

**Pull request closed without merging**
