### PR TITLE
Add WooCommerce Product Attributes to EP Facet Widget Dropdown

### PR DESCRIPTION
**Pull request by mgratch**

### CODE REVIEW

**Comment by allan23** [comment]
Hi @mgratch,

It looks like you based your branch off of master. You'll want to  base any 2.8.x changes off of `develop-2.x` and be sure to submit a PR for 3.0 (in the `develop` branch).

**Comment by pmgarman** [comment]
@allan23 this was by request, @brandwaffle mentioned starting with master since dev was now 3 alpha and wanted to get this out quick. Let us know if that's changed.

**Comment by brandwaffle** [comment]
@pmgarman @mgratch that's my bad-- @allan23 is right that the latest code for 2.8.x is in that develop-2.x branch (master is just what's currently on WP.org but doesn't contain any pending 2.x fixes). We'll branch off the develop-2.x branch and get this commit added there--it's not very large and we really appreciate the PR so happy to do that.

**Comment by pmgarman** [comment]
Cool, was going to say we can get the branches swapped around pretty quick. Thanks for the quick look at this!

**Comment by tlovett1** [comment]
@pmgarman @brandwaffle did we ever get this prepared for 3.x?

**Comment by tlovett1** [comment]
I think this was included in another PR. Feel free to reopen.

**Pull request closed without merging**
