### PR TITLE
Allows product attributes to be selectable. Resolves #1299

### LINKED ISSUE #1299: Can't select any filter. It seems like results count is zero for every term.
Have you searched for similar issues before submitting this one?

Is this a bug, question or feature request?

Describe the issue you encountered:
Can't select any filter, all is like faded out. 
Same for every filter type.
If debugging code, then $GLOBALS['ep_facet_aggs'] is empty

Current WordPress version:
5.1.1
Current ElasticPress version:
2.8.2
Current Elasticsearch version:
6.3.2
Where do you host your Elasticsearch server:
Own server
Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Woocommerce
Steps to reproduce:

1. 
2. 
3. 

Screenshots, if needed:
image

### PR DESCRIPTION
**Pull request by allan23**

### CODE REVIEW

**Comment by oscarssanchez** [comment]
@allan23  #1304 seems to be true. Faceting stops working on taxonomy archive pages.

**Comment by allan23** [comment]
@oscarssanchez can you check to see if this resolves the issue?

**Comment by allan23** [comment]
@mgratch can you test as well?

**Comment by mgratch** [comment]
Confirmed 👍

**Comment by mgratch** [comment]
@allan23 this didn't make it to .org release? :(
https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Facets/Facets.php#L205

**Comment by allan23** [comment]
@tlovett1 ?

**Comment by allan23** [comment]
This is pending in #1344

**Comment by michaeltieso** [comment]
Testing the `develop` branch here but doesn't seem to have fixed it unless I'm missing something?

**Pull request merged**
