### PR TITLE
User Search Foundation

### PR DESCRIPTION
**Pull request by johnpbloch**
This is the first of a few chunks of code to add user search to ElasticPress.

This pull request breaks post indexing and searching into a modular system and adds user indexing and searching to that system. The next few parts are:

1. Integrating ElasticPress into `WP_User_Query`
2. Integrating user indexing into WP CLI
3. Adding unit tests for new functionality

Each of these will be submitted as a pull request to the feature/user-search branch (like this one) as it's ready and the whole feature will be submitted as another pull request against develop once all parts are merged into the feature branch.

### CODE REVIEW

**Comment by tlovett1** [comment]
@johnpbloch is this ready for review?

**Comment by johnpbloch** [comment]
@tlovett1 yes-ish. This is more of a review of some of the foundational changes for user searching. If these changes need to go in a different direction, it'd be better to catch it early rather than after another huge chunk of work.

**Comment by tlovett1** [comment]
@johnpbloch loving how you are structuring this so far.

**Comment by johnpbloch** [comment]
I'm going to close this, as development has not actually happened in the way I'd hoped it would in the description of this pull request.

**Pull request closed without merging**
