### PR TITLE
When post_type is not being set in post object, it gets overwritten by g...

### PR DESCRIPTION
**Pull request by tott**
This addresses https://github.com/10up/ElasticPress/issues/183

### CODE REVIEW

**Comment by tlovett1** [comment]
Can you reopen this against `develop`?

**Comment by tott** [comment]
Will do, also thought of a better solution and will change this accordingly.

**Comment by AaronHolbrook** [comment]
Hi @tott - do you mind reopening this against develop so we can get this into the next version?

Thanks!
Aaron

**Comment by tott** [comment]
Absolutely no problem. As i noticed that my PR just addressed one particular issue i'm still working on a more general solution for mapping those attributes. Will reopen when this is in place

**Comment by tlovett1** [comment]
Somehow this already made it into develop anyway.

**Pull request closed without merging**
