### PR TITLE
Try: Co-Author Plus integration

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change

Support querying post by guest author added by Co-Author Plus.

Fixes: #1792.

### Verification Process

1. Install and activate Co-Author Plus.
2. Activate Protected content feature.
3. Add a guest author named `mike` and assign it to some posts.
4. Go to /wp-admin/edit.php?author_name=mike and see assigned posts.

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

#1792

### CODE REVIEW

**Comment by jeffpaul** [comment]
@tlovett1 do you have a preference on approach on this, specifically as integration like the initial commit (3588eea) or as a feature like the latest commit (aa01981)?

**Comment by mbanusic** [comment]
Hi, I just deployed this to my site where we extensively use Co-Author Plus. We had issues that were partially handled with modifications in #1792. This new feature fixes all of our problems. At least as far as I could test in this short period of time. All expected queries are routed to ES, and results returned are correct (visible through Query Monitor).

I have deployed it in the production, so I might have more feedback tomorrow when more editors start using the site.

**Comment by brandwaffle** [comment]
@jeffpaul @dinhtungdu @tlovett1 We're going to discuss moving this into a separate repo as its own plugin tomorrow. As we add compatibility with various plugins I want to be sure we don't end up adding too much conditional code into the main EP plugin.

**Comment by brandwaffle** [comment]
@tott I think this would be good for the Power User addon plugin. Thoughts?

**Comment by jeffpaul** [comment]
Noting here that we're holding off on pulling this into a separate repo as there's another project in-flight (can't find the issue/PR right now sorry) that may similarly create an ElasticPress add-on plugin in a separate repo, so we're looking to see how that separate workstream evolves before deciding whether the Co-Authors Plus integration makes sense to be bundled into that work.  Updates to follow...

**Comment by mckdemps** [comment]
Please move this to Elasticpress Labs.

**Comment by mckdemps** [comment]
This has been moved to EP labs.

**Comment by jeffpaul** [comment]
see: https://github.com/10up/ElasticPressLabs/pull/4

**Pull request closed without merging**
