### PR TITLE
Score/Priority on searched terms

### PR DESCRIPTION
**Pull request by fet0r**
It is possible to give priority for searched terms?
for example we want to give less score/priority for categories (taxonomies) results and put titles results in front first.

### CODE REVIEW

**Comment by tlovett1** [comment]
This needs a rebase before it can be reviewed.

**Comment by fet0r** [comment]
Can we expect it in next releases? this would be very useful, as right now the results aren't very relevant because priority for categories (taxonomies) is same or higher then post titles.

**Comment by zamoose** [comment]
@fet0r:
You'll need to perform the debase and/or issue an entirely new PR before feasibility can even be examined.x

**Comment by zamoose** [comment]
Rebase *

Darn you, autocorrect.

**Comment by fet0r** [comment]
I'm sorry, I dont know what 'rebase' term means, also not familiar with term "PR". 
Just wanted to ask if this score/priority can be done via command-line or by adding some code to functions.php.

**Comment by zamoose** [comment]
@fet0r:
`git rebase`: https://help.github.com/articles/about-git-rebase/
"PR" == "pull request" https://help.github.com/articles/using-pull-requests/

**Comment by tlovett1** [comment]
Closing this. @fet0r feel free to resubmit once it's cleaned up a bit.

**Pull request closed without merging**
