### PR TITLE
add github issue template for easier tracking issue

### PR DESCRIPTION
**Pull request by ivankristianto**
Let's standardize when the user open an issue.
I create a issue template, so we can easily replicate the issue.
Read more: https://help.github.com/articles/creating-an-issue-template-for-your-repository/

### CODE REVIEW

**Comment by tlovett1** [comment]
Perhaps this should address whether the issue is a bug, question, or feature request?

**Comment by ivankristianto** [comment]
I did add a question to ask the user whether the issue is a bug, question or feature request.

**Comment by tlovett1** [comment]
Still needs some formatting work. Take a look at the preview.

**Comment by ivankristianto** [comment]
@tlovett1 i update the formatting.

**Comment by tlovett1** [comment]
I think you overwrote my changes :/

**Comment by ivankristianto** [comment]
@tlovett1 I adjust the formatting the way I feel it's good to fill in and to read it.
And It's based from your changes. But i'm open if you need me to revert back the commit and just do a little formatting tweak.

**Comment by tlovett1** [comment]
Nice work @ivankristianto!

**Pull request merged**
