### PR TITLE
Single-site unit tests

### PR DESCRIPTION
**Pull request by petenelson**
### Description of the Change
Adds single-site phpunit XML config and updates some of the existing unit tests to work in single-site.

### Alternate Designs
None

### Benefits
Some of the current code paths are not testable due to the existing phpunit.xml.dist and bootstrap file only setting up multi-site.

### Possible Drawbacks
None

### Verification Process
Updated existing unit tests

### Checklist:
- [X] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues
None

### Changelog Entry
- Updated some unit tests to support single-site

### CODE REVIEW

**Comment by tlovett1** [comment]
Is this still WIP?

**Comment by petenelson** [comment]
I'd have to pull in all of the existing unit tests that have been merged and re-visit it.

**Comment by petenelson** [comment]
There's some errors when running the tests, both code errors and failing tests, so I'll be working on those as well as adding additional tests to improve code coverage.

**Comment by petenelson** [comment]
Still running into an issue with the one sticky post test, but that may be something with the test rather than something with the code. When all the tests run, it fails. When I run it with `--group=post` it passes (same if they are run individually). Not sure if this is a holdup for getting this merged.

**Pull request merged**
