### PR TITLE
Use proper tests checkout for WP_VERSION=latest

### PR DESCRIPTION
**Pull request by danielbachhuber**

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
+1

**Comment by allan23** [comment]
@danielbachhuber It looks like all WP 3.8 tests are failing in Travis.

**Comment by danielbachhuber** [comment]
> Fatal error: Access to undeclared static property: EP_Test_Base::$ignore_files in /home/travis/build/10up/ElasticPress/tests/includes/class-ep-test-base.php on line 11

Looks like your tests aren't properly configured to run with WordPress 3.8 tests. Do you need to keep 3.8 support?

**Comment by johnpbloch** [comment]
@danielbachhuber Could you try changing the constructor in `EP_Test_Base` to this:

```php
	/**
	 * Prevents weird MySQLi error.
	 *
	 * @since 1.0
	 */
	public function __construct() {
		if ( property_exists( __CLASS__, 'ignore_files' ) ) {
			self::$ignore_files = true;
		}
	}
```

I'd love to get this issue resolved and get tests into a useful state again, and I think that would get around the errors above

**Pull request closed without merging**
