### PR TITLE
Fix Admin GUI Usability Issues 

### PR DESCRIPTION
**Pull request by ivanlopez**
This fixes issue #507

1. I updated the copy that is displayed when a usable host is entered but Elasticsearch has not been set to override the default WordPress search.  
2. I added a WP_DEBUG check before adding the `post_submitbox_misc_actions` action to prevent the display of the index status to users that don't have WP_DEBUG enabled. 
3. When indexing is complete via the GUI I had it auto select the "Use Elasticsearch" checkbox in order to prevent accidentally disabling Elasticsearch if a user click "Save Changes".

### CODE REVIEW

**Comment by ChrisWiegman** [comment]
@tlovett1 Tested and working. This should be ready to be merged.

**Comment by tlovett1** [comment]
@ivanlopez should we merge this or wait for the UI revamp?

**Comment by ChrisWiegman** [comment]
Is a revamp something I can help with? I have nothing but time this week.

**Comment by ivanlopez** [comment]
I would wait for UI revamp.

**Comment by tlovett1** [comment]
Ok, let's merge this stuff now so we don't block 2.0

**Comment by ivanlopez** [comment]
Sure, I'll reach out to you shortly on Slack.

**Pull request merged**
