### PR TITLE
Change test to actually start adding posts on the 6th, ...

### PR DESCRIPTION
**Pull request by joeyblake**
...changed between date query to be "gte,lte" to match sql, fix test count

### CODE REVIEW

**Comment by tlovett1** [comment]
Hmm still failing.

**Comment by joeyblake** [comment]
Ha i swear that just passed locally...hmm is right. To the code!



—
Joey Blake

**Comment by joeyblake** [comment]
"When you change the number of posts created, that is going to change some of the tests" – Joey Blake
selfie-0

**Comment by tlovett1** [comment]
Thanks!

**Pull request merged**
