### PR TITLE
Order by post__in ASC/DESC support

### LINKED ISSUE #330: Adding orderby post__in support
Sorting in ES may not be possible to sort by a manual order of _id or post_id, so I think if we do get an orderby 'post__in' we'd have to sort it manually with PHP (not so great).

Here's what core does with MySQL, so I'm not sure how to accomplish that in ES. Looked around the docs but it didn't seem to be available.

``` php
        } elseif ( $q['orderby'] == 'post__in' && ! empty( $post__in ) ) {
            $orderby = "FIELD( {$wpdb->posts}.ID, $post__in )";
        } elseif ( $q['orderby'] == 'post_parent__in' && ! empty( $post_parent__in ) ) {
            $orderby = "FIELD( {$wpdb->posts}.post_parent, $post_parent__in )";
        }
```

Further, the same logic we end up using could also be used for orderby support for post_parent__in too.

### PR DESCRIPTION
**Pull request by sc0ttkclark**
#373 strikes back!

Fixes #330 

Now with tests!

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Tests passing, this is golden :)

**Comment by sc0ttkclark** [comment]
@tlovett1 is this in core now? or should I draft a new PR?

**Comment by tlovett1** [comment]
I don't think it is. Can you add a new PR?

**Comment by sc0ttkclark** [comment]
Will do in the coming week or so.

**Comment by sc0ttkclark** [comment]
New PR posted here: #903

**Pull request closed without merging**
