### PR TITLE
Media Library Search Integration

### PR DESCRIPTION
**Pull request by allan23**
### Description of the Change
This PR allows a user to enable Elasticsearch integration in the Media Library from the Protected Content settings.

### CODE REVIEW

**Comment by tlovett1** [comment]
@allan23 anyway to get a few simple unit tests?

**Comment by tlovett1** [comment]
This won't work. Currently attachments are only indexed if documents is enabled.

**Comment by oscarssanchez** [comment]
I believe this has been implemented already, shall we close this one?

**Comment by archon810** [comment]
As per @oscarssanchez above, is this PR still necessary or media search has already been implemented?

**Comment by brandwaffle** [comment]
@archon810 if you activate Protected Content all media titles will be searched. If you also activate Documents then the content of the attachments (assuming there is any) would also be searchable. This PR is definitely outdated and we'll be looking at closing it in our weekly meeting.

**Comment by brandwaffle** [comment]
Media search is now a part of the core plugin.

**Pull request closed without merging**
