### PR TITLE
Add search term highlighting

### PR DESCRIPTION
**Pull request by mlaroy**
### Description of the Change

This pull request adds a new Feature, giving the plugin the ability to inject tags around search terms in search results. Also adds an admin screen to select the tag, add a colour, and whether to include in the_excerpt, since excerpts filter out html by default.

Screen Shot 2019-11-12 at 4 31 39 PM
Screen Shot 2019-11-12 at 4 31 56 PM
Screen Shot 2019-11-12 at 4 31 13 PM

### Benefits

Search terms can be styled to stand out within search results, like you might find in any major search engine, for visual cues to how that result is relevant to your search.

### Possible Drawbacks

On the off chance that the plugin user already has styles applied to the class applied to the injected tag, it will be styled accordingly.

### Verification Process

Inspected source code, used the EP Debug Bar to confirm the query args were being properly modified using `ep_formatted_args`, as well as verifying with the debug bar the the highlighting was returned from the ElasticSearch request.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

## 2019-11-XX

* Add search term highlighting to search results
* Add new admin screen to configure highlighting settings

### CODE REVIEW

**Comment by tott** [comment]
This implements #1551

**Comment by tlovett1** [comment]
Please merge in `develop` and resolve conflicts.

**Comment by tlovett1** [comment]
This feature should not add a settings screen. The settings should be shown in the feature on the dashboard.

**Comment by tlovett1** [comment]
The spacing here looks wrong.
Screen Shot 2019-12-03 at 9 26 17 PM

**Comment by tlovett1** [comment]
Also, needs unit tests to be merged.

**Comment by oscarssanchez** [comment]
As this was pushed to Michael's fork I couldn't push more commits to it so I started a new PR here: https://github.com/10up/ElasticPress/pull/1804 

Shall we close this one ? @brandwaffle @tlovett1

**Pull request merged**
