### PR TITLE
Add support for orderby => post__in

### LINKED ISSUE #330: Adding orderby post__in support
Sorting in ES may not be possible to sort by a manual order of _id or post_id, so I think if we do get an orderby 'post__in' we'd have to sort it manually with PHP (not so great).

Here's what core does with MySQL, so I'm not sure how to accomplish that in ES. Looked around the docs but it didn't seem to be available.

``` php
        } elseif ( $q['orderby'] == 'post__in' && ! empty( $post__in ) ) {
            $orderby = "FIELD( {$wpdb->posts}.ID, $post__in )";
        } elseif ( $q['orderby'] == 'post_parent__in' && ! empty( $post_parent__in ) ) {
            $orderby = "FIELD( {$wpdb->posts}.post_parent, $post_parent__in )";
        }
```

Further, the same logic we end up using could also be used for orderby support for post_parent__in too.

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Fixes #330

- [ ] Unit test for `'orderby' => 'post__in'`
- [x] README.md documentation update
- [ ] Update `@since` if needed

### CODE REVIEW

**Comment by tlovett1** [comment]
Will merge once the unit test is added. This just orders by the order in the post__in array?

**Comment by sc0ttkclark** [comment]
That's correct, in a similar way as WP_Query does for it's orderby => post__in

**Comment by sc0ttkclark** [comment]
Another tweak needed for this, will look into it

**Comment by sc0ttkclark** [comment]
New PR posted here: #903

**Pull request closed without merging**
