### PR TITLE
Fix meta query paths

### PR DESCRIPTION
**Pull request by mmcachran**
Update meta query paths to post_meta.[KEY].raw to avoid search breaking with meta queries.

### CODE REVIEW

**Comment by allan23** [comment]
Hi @mmcachran it appears that this change causes unit tests to fail.

**Comment by dkotter** [comment]
@mmcachran As mentioned above, unit tests are now failing. If you could get those fixed up, that would be great.

Also, can you provide an example of what this fixes? You mention "avoid search breaking with meta queries" but I guess I'm not 100% clear what was actually breaking. Code looks good, besides unit tests needing fixed up, but not exactly sure what I should be testing to make sure this works as expected.

Thanks!

**Comment by mmcachran** [comment]
@dkotter the updates will fix backwards compatibility issues with the key getting changed in newer versions of the plugin. The mapping now contains fields for meta.* and postmeta.* but the search is only for meta.*. For sites using the older version of the plugin the meta.* object doesn't exist. 

If the field name is going to stay changed moving forward it may be easier to just reindex sites when upgrading the plugin rather than changing the code.

**Comment by tlovett1** [comment]
Closing this one.

We moved to the `meta` key. When upgrading from an older version you just need to reindex.

**Pull request closed without merging**
