### PR TITLE
WIP Sticky posts feature.

### PR DESCRIPTION
**Pull request by oscarssanchez**
In regards to https://github.com/10up/ElasticPress/issues/898 

Initial approach to implement sticky post feature:

- When adding initial mappings, we are adding a is_sticky field in ElasticSearch
- When indexing, we add the is_sticky value from wp_options to ES
- We set the _score of the is_sticky: true value boost so it always returns on top.

### CODE REVIEW

**Comment by oscarssanchez** [comment]
Hi @allan23 , 

Thanks for your feedback, I'll address this on upcoming commits. In the meantime, I wanted to commit some changes I did to support/fix the following:

Previously, sticky posts were displaying only when orderby was set by rand. As this is not the default on WordPress, I moved this outside and make sure to display sticky posts only on the front page, so this does not conflict when performing normal search queries.  

Also, the  `is_sticky` property was not getting updated when ES ran a update_sync. This was due to `stick_post()` running after `wp_insert_post` hence the status remained the same until we ran a manual resync.

**Comment by oscarssanchez** [comment]
- Added conditionals and mappings for 5.0 and pre 5.0

**Comment by tlovett1** [comment]
I kind of wonder how useful storing sticky posts in EP is. Right now there is just an option that references post IDs. Querying that option and each post based on ID is extremely fast already.

**Comment by oscarssanchez** [comment]
Hi @tlovett1 ,

Thanks, I see your point! This is definitely less code to execute.

**Comment by oscarssanchez** [comment]
@allan23  I included unit tests on the most recent commit, and also changed the conditional to include stickies on top from `is_front_page()` to `is_home()`

**Pull request merged**
