### PR TITLE
Update elasticpress.php

### PR DESCRIPTION
**Pull request by joelgarciajr84**
Just for security reasons

### CODE REVIEW

**Comment by tlovett1** [comment]
Good point. Shouldn't this be in other files as well?

**Comment by joelgarciajr84** [comment]
Surely , I will insert in the other files .

**Comment by joelgarciajr84** [comment]
I inserted the code in all php files. I Guess. :)

**Comment by joelgarciajr84** [comment]
:smile:

**Comment by ocean90** [comment]
This broke the unit tests, see #299.

**Pull request merged**
