### PR TITLE
Fix/wpcli sync issue

### LINKED ISSUE #713: If a user tries to WP-CLI sync during dashboard sync they are not prevented
I did try:
1. Sync in dashboard and then run index from wpcli. It doesn't prevent
2. Run index from wpcli and then Sync in dashboard. It doesn't prevent
3. Sync in dashboard in 2 different browser. It doesn't prevent 
4. Run index from wpcli in different terminal. It doesn't prevent 

Environment:
WP 4.7.2
EP 2.2
ES 5.0.0

### PR DESCRIPTION
**Pull request by ivankristianto**
Fixed #713 

What this PR do:

1. Prevent dashboard sync when wpcli index running. By checking the transient ep_wpcli_sync
2. Prevent wpcli sync when dashboard sync running. By checking transent ep_dashboard_sync

### CODE REVIEW

**Comment by tlovett1** [comment]
@ivankristianto when I start WP-CLI sync and load the dashboard, I see:
`WP CLI sync is occuring. Refresh the page to see if it's finished`

Do you not see that?

**Comment by ivankristianto** [comment]
What I fixed is:
I open the dashboard, and I start the WP CLi. Then without refresh the dashboard, I start the dashboard sync. And the dashboard sync will run. This PR is to prevent that.

**Comment by allan23** [comment]
@ivankristianto, when performing a sync from the admin dashboard, I get this:

screen shot 2017-06-05 at 8 22 35 am

However, if I start a sync from the dashboard and then try CLI, it works as expected (CLI spits out error saying that sync is in progress).

**Comment by allan23** [comment]
Thank you for your interest in contributing to ElasticPress. At the time of this writing, we are focusing our development efforts on version 3.0 in the `develop` branch, which is an entirely different codebase. We ask that you please take some time to review the new codebase and alter your pull request as needed to accommodate these major changes.

**Pull request closed without merging**
