### PR TITLE
Show a message when an indexing is stopped by the WP-CLI command

### PR DESCRIPTION
**Pull request by Rahmon**
### Description of the Change

This PR updates the Sync Page to show a message when an indexing is stopped by the WP-CLI command (`wp elasticpress stop-indexing`)

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

#2489

### CODE REVIEW

**Review by felipeelia — CHANGES_REQUESTED** [review]
@Rahmon I tried this one following these steps:
1. Started a new "full" sync in the dashboard (per page = 2 so it goes slowly)
2. Called `wp elasticpress stop-indexing` in the terminal

This is what happened:
1. I saw a `Sync interrupted by WP-CLI command` in the log (expected) but if I don't have the log opened I can't know what is happening, as `Sync in progress` is still visible.
2. The buttons didn't change, so I can still see "Pause" (but it's already "paused") and "Stop". We probably should trigger the "Stop" behavior, so people can't simply resume it from the dashboard again.
3. If I click on "Pause" the button becomes "Resume" and I see "Sync paused" in the logs. Then if I click on "Resume", it will start over.

**Comment by Rahmon** [comment]
@felipeelia when you have a chance, could you review it again?

**Comment by felipeelia** [comment]
@Rahmon , I really think the sync should trigger the exact same behavior of a stop. Right now, if someone stops the sync, it'll just "freeze" things, leaving the dashboard user no action. Let's bring that decision to the weekly sync.
Some other issues I'm seeing:
1. If I stop the sync after it started, the progress bar will go to 0%
2. If I pause it in the dashboard and stop it in the terminal, nothing happens in the dashboard. Then, if I click on resume, things will happen like step # 1

**Comment by Rahmon** [comment]
@felipeelia just to be sure, did you run `npm run build` before reviewing it?

**Comment by felipeelia** [comment]
> @felipeelia just to be sure, did you run `npm run build` before reviewing it?

yup!

**Comment by brandwaffle** [comment]
"Your indexing process has been stopped by WP-CLI and your (ElasticPress.io||Elasticsearch) index could be missing content. To restart indexing, please click the Start button or use WP-CLI commands to perform the reindex. Please note that search results could be incorrect or incomplete until the reindex finishes."

**Pull request merged**
