### PR TITLE
(Closes #414) Avoid Elasticsearch returning error 404 during post deletion

### LINKED ISSUE #414: Unable to delete post from Elasticsearch
I see in access logs below entries

"DELETE /xxxx-85//post/1526 HTTP/1.0" 404 92 "-" "WordPress/4.3.1; https://xxx.com" "-"

### PR DESCRIPTION
**Pull request by lukaspawlik**
Fixes #414

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Oh THIS

**Comment by tlovett1** [comment]
@lukaspawlik can you include an integration test that demonstrates this error?

**Comment by lukaspawlik** [comment]
@tlovett1 sure - I was a bit busy recently. I'll add test soon.

**Comment by tlovett1** [comment]
No need for a test actually.

**Pull request merged**
