### PR TITLE
Fix posts_per_page typo, keeping backwards compatibility

### LINKED ISSUE #346: posts_per_page bug in argument handling
https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L678

There's a typo, it should be `'posts_per_page'` instead of `'post_per_page'`. Will submit PR.

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Fixes #346

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Just rereading the code, further down you can see that `posts_per_page` is reference and then set for `size`, so there's some extra logic here that seems unnecessary for `post_per_page`.

**Comment by sc0ttkclark** [comment]
Dockunit passes, just says it's errored.

This doesn't really change anything, it just keeps backwards compatibility for the typo arg name for `post_per_page` and cleans up that logic so it's not at the top anymore.

Should be an easy merge.

**Comment by tlovett1** [comment]
Looks pretty good. Two things:

1. I'd like to do the check before calling `get_option` so we can avoid that if possible.
2. This change would be in EP 1.7

**Comment by tlovett1** [comment]
@sc0ttkclark see above

**Comment by allan23** [comment]
@sc0ttkclark Any update?

**Comment by sc0ttkclark** [comment]
PR updated with get_option conditional added back, except it's now looking at the proper posts_per_page argument.

**Pull request merged**
