### PR TITLE
Support more fields for tax_query including name and term_id

### LINKED ISSUE #335: Allow querying taxonomies by more than just slug
Currently, this is restricted to use only the "slug" field - Sometimes, we might know IDs or Names, and want to search by those

https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L747

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Fixes #335

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Added tests for name / term_id.

**Comment by tlovett1** [comment]
@sc0ttkclark I think this one needs fixing

**Comment by allan23** [comment]
@sc0ttkclark Any update?

**Comment by sc0ttkclark** [comment]
Fixes committed, tests running afresh now.

**Comment by allan23** [comment]
@sc0ttkclark Looks like unit test is failing.

**Comment by sc0ttkclark** [comment]
Need to figure out why tests are failing, will follow up

**Comment by sc0ttkclark** [comment]
Closing in favor of #426

**Pull request closed without merging**
