### PR TITLE
Feature/autosuggest selector

### PR DESCRIPTION
**Pull request by oscarssanchez**
Hi @allan23 ,

Can you please review this PR which addresses #1196 ?

I have updated the PR to address other CSS selectors and tested autosuggest works on other elements as well, so far I tested `input[type="text"]` to test elements and `id` to test id's. I also left untouched the default selectors so users don't have to type in the default selectors in case they already have them and also want to include new ones.

Thank you!

### CODE REVIEW

**Comment by allan23** [comment]
@oscarssanchez you have a conflict...

**Comment by oscarssanchez** [comment]
Thanks @allan23, seems like it got merge conflicts with the latest release. I fixed them now.

**Comment by allan23** [comment]
Thank you for your interest in contributing to ElasticPress. At the time of this writing, we are focusing our development efforts on version 3.0, which is an entirely different codebase. We ask that you please take some time to review the new codebase and alter your pull request as needed to accommodate these major changes.

**Comment by allan23** [comment]
@oscarssanchez is this PR still valid?

**Comment by oscarssanchez** [comment]
Closing since #1227 was merged

**Pull request closed without merging**
