### PR TITLE
WIP: Feature/mapping weighting dashboard

### LINKED ISSUE #1690: Weighting Engine: Post meta support
**Is your enhancement related to a problem? Please describe.**
Registering meta keys requires additional effort. We can manage searchable meta fields if we provide a UI on the weighting engine.

**Describe the solution you'd like**
Adding post meta capabilities to the weighting engine would be a good solution.

**Designs**
Screen Shot 2020-03-06 at 14 47 06

**Describe alternatives you've considered**

* Showing most-used meta keys with a group query and showing them for each post_type. (It's against simplicity and we might get performance issues on large-scale websites.)
* Registering post meta section for each post_type. (It didn't seem the best solution for UI. It's not easy to manage if the same key will be used across multiple post_types)

**Additional context**

We might consider showing (read-only) meta fields that registered via `ep_search_fields`.

### PR DESCRIPTION
**Pull request by mehidi258**
### Description of the Change

Closes #1690 

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Credits

Props @

### CODE REVIEW

**Comment by nickchomey** [comment]
@mehidi258 Could you provide a description, and even some screenshots, of what this is trying to achieve? I'd like to modify/improve the Search Fields & Weighting page/feature but want to make sure it is compatible/not redundant with your effort here.

**Comment by mehidi258** [comment]
> @mehidi258 Could you provide a description, and even some screenshots, of what this is trying to achieve? I'd like to modify/improve the Search Fields & Weighting page/feature but want to make sure it is compatible/not redundant with your effort here.

This PR covers `Manage Search Fields & Weighting` page redesign with react.js
Here is the video like how it's behaving with react: https://www.awesomescreenshot.com/video/10938591?key=903bdc944b9fc715d2e92b5b2c2d94af
Note: in the video looks like range-slider is not working. but actually it is working, while recording because of chrome extension that range slider was not working surprisingly.

**Comment by nickchomey** [comment]
Wow. That's very slick. @felipeelia I hope that you guys can give this some attention to get it into the next version update, along with #2812 to provide more extensability/customizability.

**Comment by JakePT** [comment]
Closing in favour of #3068.

**Pull request closed without merging**
