### PR TITLE
(Closes #439) Add GUI support for "keep active" feature

### LINKED ISSUE #439: Add --keep-active option to the admin GUI
In #401, we added an option to not disable ElasticSearch during indexing, when using the cli command. It would be nice to bring this same option over to the new admin GUI. I'm imagining something like a checkbox next to the index button, that if checked, would keep ElasticSearch enabled.

### PR DESCRIPTION
**Pull request by lukaspawlik**
- added GUI support for "keep ElasticSearch active" during reindexing feature
- ported https://github.com/10up/ElasticPress/pull/391 to GUI
- moved string from JavaScript to PHP and made it translatable

### CODE REVIEW

**Comment by allan23** [comment]
@lukaspawlik It appears that there are some issues with WP 3.7.1 and some merge conflicts that need to be resolved. Can you rebase with develop?

**Comment by lukaspawlik** [comment]
@allan23 PR has been rebased.

I checked Travis and issues with 3.7.1 look like issues with testing environment as I see

```
Error:         No code coverage driver is available
WordPress database error Can't reopen table: 'a' for query DELETE a, b FROM wptests_2_options a, wptests_2_options b WHERE......
```

**Comment by allan23** [comment]
@lukaspawlik I was able to reproduce the Travis issues by running phpunit against WP 3.7.1 locally. The real question now is why it is occurring. I don't see anything with your code that would cause it.

**Comment by lukaspawlik** [comment]
@allan23 I'll check it and will let you know if I find anything. Are okay with that?

**Comment by allan23** [comment]
@lukaspawlik Absolutely. I'm a little stumped.

**Comment by lukaspawlik** [comment]
:+1: I'll start working on it ASAP

**Comment by lukaspawlik** [comment]
@allan23 finally I was able to find the issue. WP 3.7.1 didn't support `orderby` array argument. I fixed this by making its value flat string `ID` and by adding another `WP_Query` arg `order` which is set to `DESC`. I ported this also to `wp-cli` command as it was throwing warnings on 3.7.1 too.

**Comment by allan23** [comment]
@lukaspawlik everything works as expected. However, there is just one tiny change needed:
ElasticSearch needs to be Elasticsearch to be consistent.

**Comment by tlovett1** [comment]
lowercasesdangit()

**Comment by lukaspawlik** [comment]
@allan23 :smile:  fixed - thanks for pointing that :smile:

**Comment by tlovett1** [comment]
This feature doesn't seem to be working at all.

**Pull request merged**
