### PR TITLE
Added unicode char encoding to pass through json_encode()

### PR DESCRIPTION
**Pull request by dmitryshkolnikov**
If posts contain unicode characters the indexer fail to process it. I added encoder of unicode chars in posts before feeding them to json_encode()

### CODE REVIEW

**Comment by tlovett1** [comment]
A few things:
1. This will probably need to happen in the `index_post` method of the API class
2. Please make sure you code follows the WordPress Coding Standards.
3. Are you trying to index characters in another language? Perhaps you should a different Elasticsearch analyzer.

**Comment by dmitryshkolnikov** [comment]
1. I had that issue while initial indexing. But you're right, the same encoding should be in API class.
2. Fixed.
3. No, I'm trying to index the posts in English but they contain special characters like 1/2 or 3/4 as well as specific names in Spanish and French.

**Comment by tlovett1** [comment]
@ChrisWiegman are you investigating this one?

**Comment by tlovett1** [comment]
@ChrisWiegman ?

**Comment by ChrisWiegman** [comment]
@dmitryshkolnikov Have you tried it with just wp_json_encode? While not while documented the idea is to verify all content is properly UTF-8 (see http://pento.net/2014/12/19/json-encoding-in-wordpress-4-1/)

**Comment by dmitryshkolnikov** [comment]
Yes, with wp_json_encode we have no problem with our data.

**Pull request closed without merging**
