### PR TITLE
Rename first EP submenu item to Features

### PR DESCRIPTION
**Pull request by helen**
### Description of the Change

As advertised - instead of top-level ElasticPress menu being followed by another submenu item reading ElasticPress, that submenu item will read Features.

### Alternate Designs

n/a

### Benefits

Should make it easier to understand what that page is for specifically.

### Possible Drawbacks

Not seeing any.

### Verification Process

Checked in the admin, clicked to different pages and navigated back.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tlovett1** [comment]
@oscarssanchez can you test?

**Comment by oscarssanchez** [comment]
Just saw this. Assigning to myself.

**Comment by tlovett1** [comment]
Does this work when network activated?

**Review by dinhtungdu — APPROVED** [review]
LGTM! This works on both single-site and multi-site (network activation).

**Pull request merged**
