### PR TITLE
Adds a filter to allow the indexing of specified private meta keys.

### PR DESCRIPTION
**Pull request by ChrisWiegman**
This is similar to #328 and based off @sc0ttkclark 's code but does not include any default private fields to index.

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Looks good, my vote is STILL to include thumbnails by default, but you know me :)

**Comment by ChrisWiegman** [comment]
I'm not commenting on thumbnails one way or another (personally I would like to include media information but that's a whole other matter). I just want to get potentially any field I need when I need it :smile:

**Comment by sc0ttkclark** [comment]
I humbly request you add the ability in this filter handling to support `add_filter( 'ep_prepare_meta_allowed_protected_keys', '__return_true' );` so that all protected keys can be indexed, no matter the key name.

**Comment by sc0ttkclark** [comment]
Oh hey, I can edit, so I added it :)

**Comment by ChrisWiegman** [comment]
Good catch @sc0ttkclark Fixed.

**Comment by tlovett1** [comment]
Can one of you add a unit test here?

**Comment by ChrisWiegman** [comment]
I've added tests that should be sufficient for this PR and can be expanded to better cover #328 as we move forward.

**Comment by allan23** [comment]
@tlovett1 This looks good.

**Comment by sc0ttkclark** [comment]
Do we need to add this to readme / docs?

**Comment by sc0ttkclark** [comment]
I still strongly believe that _thumbnail_id should be in the default list, but I know that Taylor is against it. Just wanted to note it :)

This will resolve the concerns I was up against in #328, although it still requires a custom filter to enable _thumbnail_id.

**Comment by allan23** [comment]
Tests are confirmed working locally and in Travis; not sure why Dockunit doesn't match. @tlovett1

**Pull request merged**
