### PR TITLE
Do not activate the module if does not meet dependency requirement

### PR DESCRIPTION
**Pull request by Ritesh-patel**

### CODE REVIEW

**Comment by tlovett1** [comment]
I'm confused on this PR. If a module's dependencies aren't met, the activate button is not available. Correct?

**Comment by Ritesh-patel** [comment]
Correct, it's not available. But can be available if we just alter HTML from source and remove a class property.

**Comment by tlovett1** [comment]
Why is that an issue? Is the use case is someone is modifying elements in the DOM manually?

**Comment by Ritesh-patel** [comment]
Yes, if someone modifies elements in DOM manually.

**Comment by Ritesh-patel** [comment]
I know it's very rare that someone will do that but upon doing that, it gives fatal error.

**Comment by tlovett1** [comment]
Can you update the PR not to update the .pot file?

**Comment by Ritesh-patel** [comment]
PR updated.

**Pull request merged**
