### PR TITLE
Update: Exclude password protected posts from search

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change
This PR is a replacement for #1789. Instead of adding a new meta, we use `has_password` argument of `WP_Query` to control the visibility of protected posts.

By default, EP doesn't index password-protected posts. They will be indexed if Protected content feature is enabled. Again, only admin queries return protected posts; this PR introduces a new filter to enabled it on the frontend: `ep_exclude_password_protected_from_search`.

### Alternate Designs
See #1789.

### Benefits
Hide password-protected posts from search results.

### Possible Drawbacks
None that I'm aware of.

### Verification Process
Reindex site contains password protected posts with Protected Content enabled. See protected posts in the admin area but not on the frontend.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues
Closes #1789

### CODE REVIEW

**Comment by dinhtungdu** [comment]
@tlovett1 Excluding password-protected posts is not the default behavior of WordPress core but it makes sense to me. Should we repect core behavior here? Given that can change it by using the new filter introduced in this PR.

**Comment by sagarsdeshmukh** [comment]
Is there any blocker in review & merging this PR?

**Comment by abdullah1908** [comment]
@dinhtungdu thank you so much for submitting MR. We'll surely take a look & bring under consideration while tech discussion would be continued.

**Comment by rebeccahum** [comment]
Hi all,

Any timeline or update on the status of this?

**Comment by rebeccahum** [comment]
Just did some testing on the current PR and I'm finding that newly created password-protected posts are still being shown in the search.

**Comment by oscarssanchez** [comment]
closing in favor of https://github.com/10up/ElasticPress/pull/2408

**Pull request closed without merging**
