### PR TITLE
#613 - Fix for attachment indexing

### PR DESCRIPTION
**Pull request by Svanmark**
Fixes the issues with attachment indexing I mentioned in #613.

Unfortunately I can't get the tests to pass. However they won't pass on the state of the code before this pull request either.

### CODE REVIEW

**Comment by tlovett1** [comment]
@Ritesh-patel can you review?

**Comment by Ritesh-patel** [comment]
@tlovett1 this looks good.
@Svanmark can you add unit test?

**Comment by tlovett1** [comment]
I don't see what this does at all. Just seems like refactoring.

**Comment by Ritesh-patel** [comment]
Yes, this pretty much looks like refactoring and hence required unit test.

**Comment by Svanmark** [comment]
Sorry guys. It should have included a fix for allowing attachments with post status "inherit" to be indexed, but that part of the code seems to be missing out from my pull request. I'll see if I can get the full code for you.

**Comment by Ritesh-patel** [comment]
Hi @Svanmark 

This PR has merge conflicts. Can you please make sure that PR is up to date with current develop branch?

Regards,
Ritesh

**Comment by tlovett1** [comment]
Also, please remove the refactoring.

**Comment by Svanmark** [comment]
Should now be up to date with develop branch and refactoring removed.

**Comment by Ritesh-patel** [comment]
This seems to be working.

**Pull request merged**
