### PR TITLE
Eager title search

### PR DESCRIPTION
**Pull request by lukaspawlik**
Add eager searching by title.

### CODE REVIEW

**Comment by tlovett1** [comment]
@lukaspawlik can you add a use case here? Thanks!

**Comment by lukaspawlik** [comment]
@tlovett1 

Most common use case is to search posts by part of title word ex:
 `post_title == Events in Washington`
 `post_title == Sport events in Washington Heights`

This allows searching by typing `wash`. Currently that kind (part of the word) of search doesn't find post from this example. This behaviour can be modified by decreasing `min_similarity`

```
'min_similarity' => apply_filters( 'ep_min_similarity', 0.75 )
```

however it produces "false positives". My idea is to allow more sensitive searching by post titles only.

**Comment by tlovett1** [comment]
Why would your search contain a SQL part? Can you give me an example search query where this would kick in?

**Comment by lukaspawlik** [comment]
@tlovett1 I can give an example how I was using ElasticPress as I didn't use any custom PHP code to use WP_Query. I installed clean WordPress site. I used Search widget on homepage for "Hello World" post searching. I just typed "wor" in search input field and what I got is:

- with ElasticPress enabled (posts were indexed in Elasticsearch) I got empty search results
- with my PR I got "Hello World" post on the list

Below is SQL query obtained via Debug Bar

> SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts WHERE 1=1 AND (((wp_posts.post_title LIKE '%wor%') OR (wp_posts.post_content LIKE '%wor%'))) AND wp_posts.post_type IN ('post', 'page', 'attachment') AND (wp_posts.post_status = 'publish' OR wp_posts.post_author = 1 AND wp_posts.post_status = 'private') ORDER BY wp_posts.post_title LIKE '%wor%' DESC, wp_posts.post_date DESC LIMIT 0, 10

If you need WP_Query object dumped please let me know.

**Comment by allan23** [comment]
@lukaspawlik I can see what you're doing here and it makes sense. 

@tlovett1 Unit tests pass and I've tested locally. Do you foresee any issue with all searches being wildcard?

**Comment by tuanmh** [comment]
> Most common use case is to search posts by part of title word ex:
> post_title == Events in Washington
> post_title == Sport events in Washington Heights
> 
> This allows searching by typing wash. Currently that kind (part of the word) of search doesn't find post from this example. This behaviour can be modified by decreasing min_similarity
> 
> 'min_similarity' => apply_filters( 'ep_min_similarity', 0.75 )
> however it produces "false positives". My idea is to allow more sensitive searching by post titles only.

Would it best to use ngram or edge-ngram in indexing to solve this problem nicely?

**Comment by tuanmh** [comment]
This is how we tweaked: 
```
$mapping['settings']['analysis']['analyzer']['default']['filter'][] =  'edge_ngram';
$mapping['settings']['analysis']['filter']['edge_ngram']['min_gram'] =  3;
$mapping['settings']['analysis']['filter']['edge_ngram']['max_gram'] =  128; //(quite bit but we're happy with this)
```

**Comment by markoheijnen** [comment]
How can you do this on title only? if the query is should then it also searches on content and excerpt. Unsure how to stop that.

Currently I add the analyzer as a custom one and add it through the filter `ep_formatted_args` with the following code: `$formatted_args['query']['bool']['should'][1]['multi_match']['analyzer'] = $args['ep_analyzer'];`

**Comment by tuanmh** [comment]
> How can you do this on title only? if the query is should then it also searches on content and excerpt. Unsure how to stop that.
> 
> Currently I add the analyzer as a custom one and add it through the filter ep_formatted_args with the following code: $formatted_args['query']['bool']['should'][1]['multi_match']['analyzer'] = $args['ep_analyzer'];

Not sure if you asked me, but you can achieve that by specify different analyser on different fields, e.g. title field with edge_gram and normal analyser for other fields.

**Comment by markoheijnen** [comment]
Was a general question and totally forgot to mention here that I did exactly that. It took me a bit to see that you can actual do that. I never looked in to the mapping part. So I added another field to I can search for post_title.ngram.

**Comment by tuanmh** [comment]
sorry @lukaspawlik for talking too much in your thread, I'm cool now :)

**Comment by lukaspawlik** [comment]
@tuanmh @markoheijnen the very basic idea of this PR was to provide more 'WP-like' search experiences without the need of tweaking anything via filters and code - some improvement for non-technical users who use ElasticPress as-is :) 

I am going to close this PR as I guess it won't get merged :)

**Pull request closed without merging**
