### PR TITLE
elasticpress_enabled to return false if host is not set

### PR DESCRIPTION
**Pull request by Svanmark**

### CODE REVIEW

**Comment by tlovett1** [comment]
It probably makes more sense to handle this in `elasticpress.php`, only including certain classes if a host is set.

**Comment by Svanmark** [comment]
Yepp, makes sense in terms of saving a bunch of bytes when loading the plugin. 

I'll have it updated. 
Thank you.

**Comment by tlovett1** [comment]
Any update?

**Comment by Svanmark** [comment]
Nothing to verify just yet, just got my fork up to date.

**Comment by Svanmark** [comment]
Seems like it's fixed already, closing. Thanks.

**Pull request closed without merging**
