### PR TITLE
Making stop_the_insanity method compatible with WordPress 4.7

### LINKED ISSUE #654: Stop_the_insanity method is not compatible with WP 4.7.
Part of the code inside the stop_the_insanity method (https://github.com/10up/ElasticPress/blob/develop/bin/wp-cli.php#L806) will throw an error on WordPress 4.7 due to changes in the hook system. See more details here: https://make.wordpress.org/core/2016/09/08/wp_hook-next-generation-actions-and-filters/

### PR DESCRIPTION
**Pull request by nicholasio**
Fixes #654

### CODE REVIEW

**Comment by tlovett1** [comment]
Is this compat with pre 4.7?

**Comment by nicholasio** [comment]
@tlovett1 Now it is. Added additional check to see if WP_Hook exists and avoid fatals with WP <  .7.

**Comment by tlovett1** [comment]
@Ritesh-patel can you test this real quick?

**Comment by Ritesh-patel** [comment]
@tlovett1 it's working fine, not throwing any notice now.

**Pull request merged**
