### PR TITLE
Feature/disable autosuggest selector

### PR DESCRIPTION
**Pull request by mlaroy**
### Description of the Change

To solve for https://github.com/10up/ElasticPress/issues/1579, this PR adds a field to enter selectors to ignore when activating autosuggest. It adds to the epas object for the JS to consume and filter out.

Screen Shot 2019-12-12 at 9 43 08 AM

Screen Shot 2019-12-12 at 9 46 14 AM

### Benefits

This will allow users to select a field to be NOT an autosuggest field, as the selector `input[type="search"]` is quite generic.

This PR also adjusts how jQuery wraps the search fields, so that having multiple search fields on a page will work properly.

### Verification Process

Tested with multiple search fields, some allowed and some ignored to ensure all were working as intended

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Added
- Add autosuggest selector field to disable autosuggest for the given selector(s)

### CODE REVIEW

**Comment by fabianmarz** [comment]
IMO the feature should be the other way round as it's way too complicated to list all search inputs. Furthermore this isn't really helpful as each search field uses the same query configuration as it's triggered via AJAX. Additionally excluding newly added search fields needs to be kept in mind when adding new plugins whose add new functionality.

To me it makes lot more sense to simply adjust the line as follows:

```diff
- const $epInput = jQuery( `.ep-autosuggest, input[type="search"], .search-field, ${  epas.selector}`  );
+ const $epInput = jQuery( `${  epas.selector}`  );
```

If you want to support all search fields however you can still use `.search-field,  input[type="search"]` as the backend input value. 🤷‍♂

**Comment by brandwaffle** [comment]
@fabianmarz I hear what you're saying but we don't want to 1) break backwards compatibility and 2) the goal of the plugin is to enable a site owner to add search to their theme without additional work when they activate the Search feature.

Are you thinking we would pre-fill the value of the backend field to the current default selector, which would then accomplish the goal of handling the issues I listed above but still enable someone to easily change those values (rather than simply being able to disable some of them)?

**Comment by fabianmarz** [comment]
@brandwaffle, yes, that's valid reasons for sure! 🙂 I think pre-fill the values as suggested by you is a good idea but may still break the backwards compatibility as the settings would have to be saved once for existing installations. To tackle this we could move the default selector set to the `localize_script`/`$epas_options section and don't make them configurable via the backend to have a "fix" set as before. As there is the `ep_autosuggest_options` filter already, devs would still be able to adjust them as the default set might interfere with 3rd party WooCommerce plugins which introduce "search" fields but provide different functionality.

Maybe something like the following:
```php
'selector' => '.ep-autosuggest, input[type="search"], .search-field,' . empty( $settings['autosuggest_selector'] ) ? 'ep-autosuggest' : esc_html( $settings['autosuggest_selector'] ),

// or maybe append them afterwards?
'selector' => empty( $settings['autosuggest_selector'] ) ? 'ep-autosuggest' : esc_html( $settings['autosuggest_selector'] ),
// … 

$epas_options['selector'] .= ', .ep-autosuggest, input[type="search"], .search-field';
```


One concern: 
> the goal of the plugin is to enable a site owner to add search to their theme without additional work when they activate the Search feature.

That's the point with Wordpress. It's popular for its easiness, huge ecosystem and variety of plugins. Most of those plugins (and themes) come with tons of configuration settings which make people doesn't require any technical skill or HTML knowledge to build pages. If such persons install plugins wich introduce fields which use fields which have one of the default selectors, they might break some functionality without noticing. That's why I think the disable approach might not be the best solution.

What do you think?

**Comment by fabianmarz** [comment]
I found the issue which I had with the default selector set: https://github.com/10up/ElasticPress/issues/1394. The facet widget adds another "search" field and broke the functionality. Not sure if this is still relevant. Will have a look and let you know.

**Comment by JakePT** [comment]
#2181 partially addressed this by adding a filter on the default selectors, so they could be excluded by a developer as needed.

**Pull request closed without merging**
