### PR TITLE
Fix/infinite loop

### PR DESCRIPTION
**Pull request by ivankristianto**
This is another option to fix for infinite loop while doing indexing.

If we merge this, then the other PR #764 and #755 are unnecessary.

### CODE REVIEW

**Comment by tlovett1** [comment]
I might like this better than removing `the_content` filter. Thoughts @allan23 ?

**Comment by allan23** [comment]
@ivankristianto your branch produces PHP warnings and notices:
```[11-Apr-2017 14:52:34 UTC] PHP Warning:  Missing argument 2 for EP_Sync_Manager::action_queue_meta_sync() in /srv/www/plugindev/htdocs/wp-content/plugins/ElasticPress/classes/class-ep-sync-manager.php on line 94
[11-Apr-2017 14:52:34 UTC] PHP Warning:  Missing argument 3 for EP_Sync_Manager::action_queue_meta_sync() in /srv/www/plugindev/htdocs/wp-content/plugins/ElasticPress/classes/class-ep-sync-manager.php on line 94
[11-Apr-2017 14:52:34 UTC] PHP Warning:  Missing argument 4 for EP_Sync_Manager::action_queue_meta_sync() in /srv/www/plugindev/htdocs/wp-content/plugins/ElasticPress/classes/class-ep-sync-manager.php on line 94
[11-Apr-2017 14:52:34 UTC] PHP Notice:  Undefined variable: object_id in /srv/www/plugindev/htdocs/wp-content/plugins/ElasticPress/classes/class-ep-sync-manager.php on line 107
[11-Apr-2017 14:52:34 UTC] PHP Notice:  Undefined variable: object_id in /srv/www/plugindev/htdocs/wp-content/plugins/ElasticPress/classes/class-ep-sync-manager.php on line 119
[11-Apr-2017 14:52:34 UTC] PHP Notice:  Undefined variable: object_id in /srv/www/plugindev/htdocs/wp-content/plugins/ElasticPress/classes/class-ep-sync-manager.php on line 132
[11-Apr-2017 14:52:34 UTC] PHP Notice:  Undefined variable: meta_key in /srv/www/plugindev/htdocs/wp-content/plugins/ElasticPress/classes/class-ep-sync-manager.php on line 135 
```

(CC: @tlovett1 )

**Comment by ivankristianto** [comment]
@allan23 I fixed it in the last commit. can you test again?

**Comment by yeszao** [comment]
Hi, I had tested ElasticPress 3.2 on my server and 3.1.4 on my local pc, they all loop infinitely. My WP version is 5.2.3.

Here is the video captured from my server:

elasticpress

**Comment by tlovett1** [comment]
@yeszao can you refresh your browser cache? I haven't seen anything like that

**Comment by yeszao** [comment]
I trying debug with chrome and find some information.
```javascript
function sync() {
	jQuery.ajax( {
		method: 'post',
		url: ajaxurl,
		data: {
			action: 'ep_index',
			feature_sync: featureSync,
			nonce: epDash.nonce
		}
	} ).done( ( response ) => {
        //...
```
The response.data return like this:
```javascript
response.data: Object
current_sync_item:
  blog_id: 1
  indexable: "post"
  url: "http://www.mywp.com"
__proto__: Object
feature_sync: "false"
found_items: 13
offset: 0
start: true
sync_stack: []
...
```
Is that mean the data return from WP admin is incurrect?

**Pull request merged**
