### PR TITLE
Add filter to support indexing revisions

### PR DESCRIPTION
**Pull request by elliott-stocks**
### Description of the Change
Add support for indexing revisions when updating/deleting posts.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Changelog Entry

- Add support for indexing revisions via the `ep_index_revisions` filter.

### CODE REVIEW

**Comment by adamsilverstein** [comment]
This looks good @elliott-stocks! Do we need to document this filter anywhere?

**Comment by elliott-stocks** [comment]
Thanks for the quick review, @adamsilverstein ! I don't think we document filters (not that I've seen anyway).

**Comment by adamsilverstein** [comment]
> I don't think we document filters (not that I've seen anyway).

Yea, I didn't see any documentation in the code, I thought perhaps it lived elsewhere :) I'll try to open a issue around adding filter docs.

For the `Distributor` plugin we are working towards generating filter docs based on our inline JSDoc notations (which we would need to add here first), see https://github.com/10up/distributor/pull/448

**Comment by tlovett1** [comment]
@brandwaffle did we figure out what we are doing with revisions?

**Comment by brandwaffle** [comment]
@tlovett1 yes, we're going to implement this change to not index revisions by default but provide a filter if needed.

**Comment by tlovett1** [comment]
Fixed in a slightly different way in #1640

**Pull request closed without merging**
