### PR TITLE
Remove duplicate category_name, cat and tag_id from ES query when tax_query set

### LINKED ISSUE #1896: Duplicate Filters in category_name when tax_query is set using OR
**Describe the bug**
Previously, `category_name` was ignored if `tax_query` was set in #501 due to this [core backwards compat feature](https://github.com/WordPress/WordPress/blob/5d99107bf3ab35aa3dda82c6b3903f5717771335/wp-includes/class-wp-query.php#L2163-L2164). However, I'm seeing that in #1617, this logic that account for that has been removed.

**Steps to Reproduce**
1) Offload a WP_Query to EP like below:

```
$args = array(
    'post_type' => 'post',
    'tax_query' => array(
        'relation' => 'OR',
        array(
            'taxonomy' => 'post_tag',
            'field'    => 'slug',
            'terms'    => array( 'canada-traffic' ),
        ),
        array(
                        'relation' => 'AND',
                        array(
                    'taxonomy' => 'region',
                    'field'    => 'slug',
                    'terms'    => array( 'Canada' ),
                        ),
                        array(
                                'taxonomy' => 'category',
                                'field'    => 'slug',
                                'terms'    => array( 'traffic' ),
                        ),
        ),
    ),
);
```

2) Returns an ES query:

```
{
    "from": 0,
    "size": 10,
    "sort": [
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "match_all": {
            "boost": 1
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "should": [
                            {
                                "terms": {
                                    "terms.post_tag.slug": [
                                        "canada-traffic"
                                    ]
                                }
                            },
                            {
                                "bool": {
                                    "must": [
                                        {
                                            "terms": {
                                                "terms.region.slug": [
                                                    "Canada"
                                                ]
                                            }
                                        },
                                        {
                                            "terms": {
                                                "terms.category.slug": [
                                                    "traffic"
                                                ]
                                            }
                                        }
                                    ]
                                }
                            },
                            {
                                "terms": {
                                    "terms.category.slug": [
                                        "traffic"
                                    ]
                                }
                            },
                            {
                                "terms": {
                                    "terms.category.term_id": [
                                        123456
                                    ]
                                }
                            },
                            {
                                "terms": {
                                    "terms.post_tag.term_id": [
                                        123455
                                    ]
                                }
                            }
                        ]
                    }
                },
                {
                    "terms": {
                        "post_type.raw": [
                            "post"
                        ]
                    }
                },
                {
                    "term": {
                        "post_status": "publish"
                    }
                }
            ]
        }
    }
}
``` 

3) Since `category_name` is populated by core, we end up with extra filters on the "SHOULD" part of the query, due to `$args['category_name']`, `$args['cat']` and `args['tag']` being set.  Therefore, we're seeing posts that don't meet the proper conditions (i.e. posts with just the "traffic" category) being returned in the results.

**Expected behavior**

Posts being returned meet either conditions:
1) post_tag = canada-traffic
OR
2) category = traffic AND region = Canada

### PR DESCRIPTION
**Pull request by rebeccahum**
### Description of the Change

Fixes #1896. Core has a funky backwards compat feature where category_name, cat and tag_id are explicitly set: https://github.com/WordPress/WordPress/blob/5d99107bf3ab35aa3dda82c6b3903f5717771335/wp-includes/class-wp-query.php#L2193-L2215.  However, this is interfering with the ES query when tax_query is set by creating duplicate filters from it.

### Alternate Designs

I didn't consider any alternative designs since this was previously patched in and wanted to follow a similar pattern to  https://github.com/10up/ElasticPress/pull/501. However, the patch was overwritten via https://github.com/10up/ElasticPress/pull/1617.

### Benefits

No more duplicate filters in the ES query!

### Possible Drawbacks

N/A

### Verification Process
1) Offload a WP_Query to ES:

```
$args = array(
    'post_type' => 'post',
    'tax_query' => array(
        'relation' => 'OR',
        array(
            'taxonomy' => 'post_tag',
            'field'    => 'slug',
            'terms'    => array( 'canada-traffic' ),
        ),
        array(
                        'relation' => 'AND',
                        array(
                    'taxonomy' => 'region',
                    'field'    => 'slug',
                    'terms'    => array( 'Canada' ),
                        ),
                        array(
                                'taxonomy' => 'category',
                                'field'    => 'slug',
                                'terms'    => array( 'traffic' ),
                        ),
        ),
    ),
);
```

2) Inspect the ES query generated and notice the extra filters:

```
{
    "from": 0,
    "size": 10,
    "sort": [
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "match_all": {
            "boost": 1
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "should": [
                            {
                                "terms": {
                                    "terms.post_tag.slug": [
                                        "canada-traffic"
                                    ]
                                }
                            },
                            {
                                "bool": {
                                    "must": [
                                        {
                                            "terms": {
                                                "terms.region.slug": [
                                                    "Canada"
                                                ]
                                            }
                                        },
                                        {
                                            "terms": {
                                                "terms.category.slug": [
                                                    "traffic"
                                                ]
                                            }
                                        }
                                    ]
                                }
                            },
                            {
                                "terms": {
                                    "terms.category.slug": [
                                        "traffic"
                                    ]
                                }
                            },
                            {
                                "terms": {
                                    "terms.category.term_id": [
                                        123456
                                    ]
                                }
                            }
                        ]
                    }
                },
                {
                    "terms": {
                        "post_type.raw": [
                            "post"
                        ]
                    }
                },
                {
                    "terms": {
                        "post_status": [
                            "publish"
                        ]
                    }
                }
            ]
        }
    },
    "track_total_hits": true
}
```

You'll observe the duplicate filters applied here:

```
 {
                                "terms": {
                                    "terms.category.slug": [
                                        "traffic"
                                    ]
                                }
                            },
                            {
                                "terms": {
                                    "terms.category.term_id": [
                                        123456
                                    ]
                                }
                            }
```

3) Apply patch and viola! They should no longer be present.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Applicable Issues

#1896

### Changelog Entry

Fixed duplicate category or tag filters when tax_query is set.

### CODE REVIEW

**Comment by felipeelia** [comment]
Hi @rebeccahum, it seems one of the unit tests failed. Do you mind taking a look? Thanks!

**Comment by rebeccahum** [comment]
@felipeelia Hiya! I've fixed the failing test now, can you please approve the running workflow?

**Comment by felipeelia** [comment]
Thank you very much @rebeccahum! I've approved the workflow again.

It looks like #2242 is related to the bug you are solving here but there seems to be yet another problem directly related to it. Just out of curiosity, is that by any chance something you are also facing?

**Comment by rebeccahum** [comment]
@felipeelia I was able to reproduce #2242 and it looks like my PR fixes that as well.

**Comment by rebeccahum** [comment]
@felipeelia I was able to reproduce that additional but in regards to the `terms.category.slug`....but I believe that is a separate issue.

**Review by oscarssanchez — APPROVED** [review]

**Comment by oscarssanchez** [comment]
Thanks for this @rebeccahum!

**Pull request merged**
