### PR TITLE
Fixed #304 allow recursively terms indexing

### LINKED ISSUE #304: Improvement: allow recursively terms indexing
Hi guys, thanks again for a great and extensible plugin. Just a suggestion. With current terms indexing, we run into a problem that if a post's term (e.g. ``optimization``) is under other terms, for example: ``computer science -> performance -> optimization``, we will not be able to search for that post under ``computer science`` or ``performance`` term. Hence, it would be handy if we can also allow 'computer science', 'performance' in the list of terms along with 'optimization'. 

It may not be suitable with other people though, so I suggest we enable both options by exposing the a filter so it can be overridden.

### PR DESCRIPTION
**Pull request by tuanmh**

### CODE REVIEW

**Comment by allan23** [comment]
@tuanmh Any chance you can rebase?

**Comment by tuanmh** [comment]
@allan23 rebased from develop, first time I did it so hopefully it is as you wished.

**Comment by tlovett1** [comment]
@tuanmh can we get this squashed into no more than a few commits? Also, there are some formatting issues.

**Comment by allan23** [comment]
@tuanmh This might help in regards to the code formatting: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/

**Pull request closed without merging**
