### PR TITLE
Account for password protected posts via protected_content feature

### PR DESCRIPTION
**Pull request by rebeccahum**
### Description of the Change

This PR piggybacks off of the logic in #1913 - however, there were [still some bugs in that PR](https://github.com/10up/ElasticPress/pull/1913#issuecomment-942717285) so they should be fixed now. Added tests as well.

### Benefits

Password protected posts will no longer unexpectedly show up in the front-end search, but will in the admin search.

### Possible Drawbacks

None that comes to mind.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

Fixed: Account for password protected posts via protected_content feature

### CODE REVIEW

**Comment by oscarssanchez** [comment]
Hi @rebeccahum ,

Thanks for submitting the PR!

I have done some preliminary testing and have this feedback:

* Logged in as an admin: The default WP behavior is to show the protected password posts on the frontend, but if you are logged out, you should not see those. 
* We should probably account for `exclude_protected_posts()` to be compatible with other algos:   https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L1338 when I tried the previous algo, this didn't work.

**Comment by oscarssanchez** [comment]
Hi @rebeccahum ,

Also forgot to mention, if you don't have the bandwidth which I know sometimes is the case, just let us know and I can pick things from here, of course giving the appropriate credit.

**Comment by rebeccahum** [comment]
@oscarssanchez Thanks so much for testing. I haven't had a chance yet to pick this back up — if you'd like to pick it up on my behalf, that'd be awesome!

**Comment by rebeccahum** [comment]
> The default WP behavior is to show the protected password posts on the frontend, but if you are logged out, you should not see those.

@oscarssanchez  On a vanilla install, I'm seeing that the protected password posts are displayed (not the content) when logged in as an admin in the front-end — same with being logged out.

**Comment by oscarssanchez** [comment]
Hi @rebeccahum ,

Yes, I should have specified the testing scenario. It should go like this:

- If I'm an admin, I see the post title displayed in the front page, and on search results.
- If I'm a subscriber, I see the post title displayed in the front page, and on search results.
- If I'm logged out, I see the post title displayed in the front page, but not on search results.

**Pull request merged**
