### PR TITLE
WP-CLI index by post type

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Also cleans up private _index_helper() method to support more args long term.

Usage:

`wp elasticpress index --post-type="my_cpt1,my_cpt3"`

The example above will only index `my_cpt1` and `my_cpt3`, it will not index `my_cpt2` or `post` or any other indexable post type that may be registered. Super handy for splitting up large indexing jobs into multiple processes.

### CODE REVIEW

**Comment by tlovett1** [comment]
@sc0ttkclark this will need some changes to `README.md` as well.

**Comment by allan23** [comment]
@sc0ttkclark Any update for this one?

**Comment by sc0ttkclark** [comment]
Added information to readme, ready for merge review.

**Comment by sc0ttkclark** [comment]
Did a manual merge of develop into this branch to fix the conflicts from `--show-bulk-errors` being merged in before this.

**Comment by tlovett1** [comment]
Assigning to Allen for testing.

**Comment by allan23** [comment]
@tlovett1 This is good to go.

**Pull request merged**
