### PR TITLE
Support term id and name tax queries; add raw/sortable to property to term mapping; add raw/sortable property to meta mapping; add raw/sortable to author display name and login

### PR DESCRIPTION
**Pull request by tlovett1**
This PR adds some missing functionality to taxonomies (term IDs), adds a sortable field to all the things, and adds some missing raw properties.

* Support `term_id` for `field` in `tax_query`
* Support `name` for `field` in `tax_query`
* Adds `name_raw` to term mapping since we need an unanalyzed version of the name property to compare against. CC @sc0ttkclark 
* Support `sortable` and `raw` properties for `post_name.login` and `post_name.display_name`
* Support `sortable` and `raw` properties for `meta.value`
* Test all the things

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Looks good and I can add a PR for a test on ordering by term name_raw too. I'm not sure what's up with the fail on term name lookup test fail though.

**Comment by sc0ttkclark** [comment]
Oh I see it, we're not passing name_raw during preparing of the terms.

**Comment by sc0ttkclark** [comment]
This fixes #335

**Comment by tlovett1** [comment]
@sc0ttkclark I'm going to merge since it's passing and getting massive. Anything else just open up another PR.

**Comment by sc0ttkclark** [comment]
Sounds good, I was thinking about adding the same tweak for post author display name / login, but you beat me to it :)

**Pull request merged**
