### PR TITLE
User indexing

### PR DESCRIPTION
**Pull request by jedibrillo**
Still a work in progress, but here are the first steps to getting users indexed and searchable via ElasticPress. I took the code/approach from @johnpbloch s code ( #369) from earlier this year and the current module approach in 2.1

All the tests are currently passing, Im sure there are more that could be added. Im also planning to update the user module to index BuddyPress extended profile data (if present).

With this PR I want it to be known this work is being done and get any feedback.

Ill be updating the PR over the next few days with additional functionality.

### CODE REVIEW

**Comment by tlovett1** [comment]
Thanks, @jedibrillo. Beware that we are changing the module registration API a little bit in 2.2 (nothing major). Also, I know @ivanlopez was planning on working on this too. Maybe you guys can collaborate.

**Comment by bliles** [comment]
@jedibrillo this work is exactly what I need, is there anything I can do to help?

**Comment by mattonomics** [comment]
@tlovett1 Would adding this mean that user data would be publicly queryable?

**Comment by tlovett1** [comment]
Nope, it wouldn't.

**Comment by lkraav** [comment]
Did interest in this die in the meanwhile?

**Comment by AustinTBiggs** [comment]
What's the state of this? 😃

**Comment by allan23** [comment]
Thank you for your interest in contributing to ElasticPress. At the time of this writing, we are focusing our development efforts on version 3.0 in the `develop` branch, which is an entirely different codebase. We ask that you please take some time to review the new codebase and alter your pull request as needed to accommodate these major changes.

**Pull request closed without merging**
